### ISSUE TITLE
Update Image Viewer

### ISSUE THREAD

**Issue by qaidjoharj53** [mohitahlawat2001/gallery-app#2]
I will add card component for viewing the image more interactively.

**Comment by mohitahlawat2001** [comment]
add photo before and after making changes!

**Comment by qaidjoharj53** [comment]
Before
![Screenshot 2023-10-04 001038](https://github.com/mohitahlawat2001/gallery-app/assets/113633954/5e7f46f0-6df9-474a-8f6f-b658dd0b2c07)



After
![Screenshot 2023-10-04 004803](https://github.com/mohitahlawat2001/gallery-app/assets/113633954/6199ccae-5cb0-43cf-ab2a-ad4703c6450c)

**Comment by qaidjoharj53** [comment]
I have made following changes:-
- I have used card component instead of modals
- I have added scrolling under card component to be able to see all the details by scrolling
- I have added a feature that allows you to get back to all photos whenever you click either on `close` button or anywhere on the screen.
