### ISSUE TITLE
[BUG]: - Alignments of the Images

### ISSUE THREAD

**Issue by rohitdubey1352** [mohitahlawat2001/gallery-app#7]
1) Alignments of the images is not in center.
2) With that I want to change the color scheme to make this attractive to any user.

Assign me this task to fix this issue @mohitahlawat2001?

**Comment by qaidjoharj53** [comment]
@rohitdubey1352 
I have already fixed it in my recent PR.

Please review it @mohitahlawat2001 .

**Comment by rohitdubey1352** [comment]
Hey, @mohitahlawat2001 Can you attach the Hacktoberfest accept badge on this task.
